name: Pipeline actions
run-name: ${{ github.actor }} is testing
on: [push]
jobs:
  Python-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Run Test
        run: python -m unittest Test.py
      - uses: actions/checkout@v1
      - run: composer install --ansi --no-progress --no-interaction --prefer-dist
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r file.zip skript.py
      - uses: actions/upload-artifact@v2
        with:
          name: file.zip
          path: ''

