name: Pipeline actions
run-name: ${{ github.actor }} is testing
on: [push]
jobs:
  Python-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Install Unittest
        run: pip install unittest --latest
      - name: Run Test
        run: pytest Tests.py

